### ISSUE TITLE
Automatically create a release of the code every week

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/SpeechTranscription#130]
**Describe the feature that you would like added**
We currently have to manually create a release any time that the code is changed. However, we would like to automate this process to occur every week (assuming that there are changes)

**Tasks that need to completed for this feature**

- [ ] Create a pipeline that runs every week and does the following:
  - [ ] Checks if there have been any changes made since the last release
  - [ ] Create a tag with a version number incremented from the previous release
  - [ ] Using the tag and Windows executable zip file of the most recent commit, create a new release
