### ISSUE TITLE
Modify the documentation to be more clear and concise

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/SpeechTranscription#132]
There is currently a lot of documentation in the README file, and some of it is unnecessary. It should be modified to look nicer

**Tasks that need to completed for this issue**
- [x] Remove the "requirements include" section of the documentation
- Contributing as a Developer section
  - Development Environment
    - [x] Change item 1 to just say "Clone the repository using 'git clone'"
    - [x] Change item 2 to just say "Install a compatible version of Python (list the compatible versions here) and run 'pip install requirements.txt'". Add a sentence that some requirements need special methods to install, and to check requirements.txt.
    - [x] Remove item 3
  - [x] Remove the "Using GitHub issues" section
  - Creating an Executable
    - [x] Add a note at the top of the section that explains that an executable is automatically generated using GitHub Actions
    - [x] Remove the numbered list, and replace it with a sentence about the option to create the executable manually using pyinstaller (refer them to the GitHub Action, which has the proper commands to run)
  - [x] Condense the "Python Version" section and add it somewhere in the second item of the Development Environment section (as mentioned previously)
- Getting started with SALTIFY section
  - [x] Move this section to above the "Contributing as a Developer section
  - [x] Add a short paragraph about the basics of using the application
- [x] Remove the entire "Using the Application" section, as it is outdated and way too long
