### ISSUE TITLE
Add a checkbox that asks whether or not you want to enable diarization

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/SpeechTranscription#133]
**Describe the feature that you would like added**
The user should be able to choose if they want to diarize when transcribing.

**Tasks that need to completed for this feature**
- [ ] Add a checkbox/switch that says "Enable Diarization?"
- [ ] If the user has this option checked:
  - [ ] Give a confirmation popup that says diarization will likely be slower than just transcription
  - [ ] Use the diarizeAndTranscribe function instead of the transcribe one
